//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerProject.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagerProject.Helper.ViewText", typeof(ViewText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;color: #5e9ca0;&quot;&gt;INFORMATION OF SUBMITTER : {0}&lt;/h1&gt;
        ///&lt;table style=&quot;border-collapse: collapse; width: 63.1215%; height: 85px;&quot; border=&quot;1&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr style=&quot;height: 17px;&quot;&gt;
        ///&lt;td style=&quot;width: 24.6216%; height: 17px; text-align: center;&quot;&gt;StudentID&lt;/td&gt;
        ///&lt;td style=&quot;width: 38.5908%; height: 17px; text-align: center;&quot;&gt;{1}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr style=&quot;height: 17px;&quot;&gt;
        ///&lt;td style=&quot;width: 24.6216%; height: 17px; text-align: center;&quot;&gt;Full name&lt;/td&gt;
        ///&lt;td style=&quot;width: 38.5908%; height: 17px; text-align: cent [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CONTENT_EMAIL_ADD_NEW_SUBMITTION {
            get {
                return ResourceManager.GetString("CONTENT_EMAIL_ADD_NEW_SUBMITTION", resourceCulture);
            }
        }
    }
}
